# Generated by Django 4.1.3 on 2023-04-06 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('location', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='artist',
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_id',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='concert',
            name='referring_artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='concert', to='app.artist'),
        ),
        migrations.AddField(
            model_name='concert',
            name='referring_venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='app.venue'),
        ),
    ]
