# Generated by Django 4.1.3 on 2023-01-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_access_token_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
