# Generated by Django 4.1.3 on 2023-04-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_venue_remove_concert_artist_concert_concert_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='referring_venue',
        ),
    ]
