# Generated by Django 4.1.3 on 2023-03-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_access_token_user_city_user_favorite_artists_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('concerts', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
