# Generated by Django 4.1.3 on 2023-02-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Artist',
        ),
    ]
