# Generated by Django 4.1.3 on 2023-04-28 23:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_concert_referring_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='lat',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='lon',
            field=models.CharField(default=29.02, max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='top_artists', to='app.user'),
        ),
    ]
