# Generated by Django 4.1.3 on 2023-04-29 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_concert_lat_concert_lon_alter_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
    ]
