# Generated by Django 4.1.3 on 2023-02-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_employee_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
