# Generated by Django 4.1.3 on 2023-04-29 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_artist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
    ]
