# Generated by Django 4.1.3 on 2023-04-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_concert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='concerts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='app.user'),
        ),
        migrations.AddField(
            model_name='concert',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='concert', to='app.user'),
        ),
    ]
