# Generated by Django 4.1.3 on 2023-04-29 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_concert_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='airline',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='flight_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='flight_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='flight_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='flight_to',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
    ]
